// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh9ppAtEJ72_Nki7k8nePCmBHNxc_yLNA',
    appId: '1:1070766224028:web:590be4e5f71a71edc1b359',
    messagingSenderId: '1070766224028',
    projectId: 'unihack24-vanjo',
    authDomain: 'unihack24-vanjo.firebaseapp.com',
    storageBucket: 'unihack24-vanjo.firebasestorage.app',
    measurementId: 'G-5DMFM25EDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGdtfrkWb40tNf7M4xwicuhCBEVTTajzw',
    appId: '1:1070766224028:android:ba4803191698741ac1b359',
    messagingSenderId: '1070766224028',
    projectId: 'unihack24-vanjo',
    storageBucket: 'unihack24-vanjo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsFuQSBwpSPR73vexNRaslQ8I43c9dzc4',
    appId: '1:1070766224028:ios:474e56b8054f9558c1b359',
    messagingSenderId: '1070766224028',
    projectId: 'unihack24-vanjo',
    storageBucket: 'unihack24-vanjo.firebasestorage.app',
    iosBundleId: 'com.example.unihack24Vanjo',
  );
}
